window.STORIES = [
  {
    "cn": "China·盘古开天",
    "en": "Pangu Shapes Heaven and Earth (China)",
    "country": "China",
    "region": "EastAsia",
    "lat": 34.58,
    "lng": 102.98,
    "category": "Moon",
    "era": "Ancient",
    "summary": "混沌中巨人劈开天地，清气为天浊气为地，奠定宇宙秩序想象。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "China·女娲补天",
    "en": "Nüwa Mends the Sky (China)",
    "country": "China",
    "region": "EastAsia",
    "lat": 34.89,
    "lng": 103.39,
    "category": "Flood",
    "era": "Ancient",
    "summary": "天柱折后炼石补苍穹，兼抟土造人，体现再生与伦理起源。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "China·后羿射日",
    "en": "Hou Yi Shoots the Suns (China)",
    "country": "China",
    "region": "EastAsia",
    "lat": 35.2,
    "lng": 103.8,
    "category": "Sun",
    "era": "Ancient",
    "summary": "十日并出时神射手救民，太阳运行与旱涝叙事的经典母题。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "China·嫦娥奔月",
    "en": "Chang'e Flees to the Moon (China)",
    "country": "China",
    "region": "EastAsia",
    "lat": 35.51,
    "lng": 104.21,
    "category": "Moon",
    "era": "Ancient",
    "summary": "不死药与月宫孤寂，象征永恒与人间别离。",
    "sourceType": "Legend",
    "confidence": "High"
  },
  {
    "cn": "China·牛郎织女",
    "en": "Cowherd and Weaver (China)",
    "country": "China",
    "region": "EastAsia",
    "lat": 35.82,
    "lng": 104.62,
    "category": "Love",
    "era": "Folk",
    "summary": "银河为界一年一度的鹊桥，承载爱情与天文节律。",
    "sourceType": "Folk Tale",
    "confidence": "High"
  },
  {
    "cn": "China·白蛇传",
    "en": "Legend of the White Snake (China)",
    "country": "China",
    "region": "EastAsia",
    "lat": 34.58,
    "lng": 102.98,
    "category": "Love",
    "era": "Medieval",
    "summary": "西湖断桥与人妖之恋，水漫金山与慈悲主题交织。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "China·大禹治水",
    "en": "Yu Tames the Waters (China)",
    "country": "China",
    "region": "EastAsia",
    "lat": 34.89,
    "lng": 103.39,
    "category": "Flood",
    "era": "Ancient",
    "summary": "疏导而非堵截的治水史诗，王权与公共工程合法性叙事。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "China·精卫填海",
    "en": "Jingwei Fills the Sea (China)",
    "country": "China",
    "region": "EastAsia",
    "lat": 35.2,
    "lng": 103.8,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "衔微木以填沧海，意志对抗命运的象征性寓言。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "China·神农尝百草",
    "en": "Shennong Tastes Herbs (China)",
    "country": "China",
    "region": "EastAsia",
    "lat": 35.51,
    "lng": 104.21,
    "category": "Fire",
    "era": "Ancient",
    "summary": "为辨药性亲尝草木，农耕与医药文明的开创神话。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "China·夸父逐日",
    "en": "Kuafu Chases the Sun (China)",
    "country": "China",
    "region": "EastAsia",
    "lat": 35.82,
    "lng": 104.62,
    "category": "Sun",
    "era": "Ancient",
    "summary": "逐日至渴死，杖化邓林，关于极限与自然的悲壮想象。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "China·哪吒闹海",
    "en": "Nezha Shakes the Sea (China)",
    "country": "China",
    "region": "EastAsia",
    "lat": 34.58,
    "lng": 102.98,
    "category": "Dragon",
    "era": "Classical",
    "summary": "灵童与龙族冲突，割肉还亲与莲花化身，流传极广。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "China·孟姜女哭长城",
    "en": "Lady Meng and the Wall (China)",
    "country": "China",
    "region": "EastAsia",
    "lat": 34.89,
    "lng": 103.39,
    "category": "Love",
    "era": "Folk",
    "summary": "长城下寻夫哭塌城垣，民间对苛役与忠贞的控诉。",
    "sourceType": "Folk Tale",
    "confidence": "Medium"
  },
  {
    "cn": "China·梁山伯与祝英台",
    "en": "Liang Shanbo and Zhu Yingtai (China)",
    "country": "China",
    "region": "EastAsia",
    "lat": 35.2,
    "lng": 103.8,
    "category": "Love",
    "era": "Medieval",
    "summary": "化蝶结局的殉情传说，与书院文化及性别规训相关。",
    "sourceType": "Folk Tale",
    "confidence": "High"
  },
  {
    "cn": "China·年兽与爆竹",
    "en": "The Nian Beast and Firecrackers (China)",
    "country": "China",
    "region": "EastAsia",
    "lat": 35.51,
    "lng": 104.21,
    "category": "Fire",
    "era": "Folk",
    "summary": "岁末驱邪的声响与红色禁忌，节令仪式的叙事来源之一。",
    "sourceType": "Folk Tale",
    "confidence": "Medium"
  },
  {
    "cn": "China·灶王爷上天",
    "en": "The Kitchen God Ascends (China)",
    "country": "China",
    "region": "EastAsia",
    "lat": 35.82,
    "lng": 104.62,
    "category": "Moon",
    "era": "Folk",
    "summary": "腊月廿三禀报人间善恶，糖瓜粘嘴的诙谐年俗故事。",
    "sourceType": "Folk Tale",
    "confidence": "Low"
  },
  {
    "cn": "Greece·奥林匹斯秩序",
    "en": "Order of Olympus (Greece)",
    "country": "Greece",
    "region": "Mediterranean",
    "lat": 37.36,
    "lng": 22.91,
    "category": "Sun",
    "era": "Ancient",
    "summary": "宙斯家族确立神界法则，雷电作为权威象征。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Greece·普罗米修斯盗火",
    "en": "Prometheus Brings Fire (Greece)",
    "country": "Greece",
    "region": "Mediterranean",
    "lat": 37.67,
    "lng": 23.32,
    "category": "Fire",
    "era": "Ancient",
    "summary": "为人类盗取天火而受鹰啄之刑，文明与代价的母题。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Greece·珀耳塞福涅与四季",
    "en": "Persephone and the Seasons (Greece)",
    "country": "Greece",
    "region": "Mediterranean",
    "lat": 37.98,
    "lng": 23.73,
    "category": "Love",
    "era": "Ancient",
    "summary": "冥府石榴籽决定母亲悲冬与大地回春。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Greece·俄耳甫斯冥府寻妻",
    "en": "Orpheus Descends (Greece)",
    "country": "Greece",
    "region": "Mediterranean",
    "lat": 38.29,
    "lng": 24.14,
    "category": "Moon",
    "era": "Ancient",
    "summary": "回望失去欧律狄刻，音乐与死亡边界的经典悲剧。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Greece·特洛伊木马",
    "en": "The Trojan Horse (Greece)",
    "country": "Greece",
    "region": "Mediterranean",
    "lat": 38.6,
    "lng": 24.55,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "智取坚城与神谕纠缠，史诗政治与背叛主题。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "Greece·奥德修斯的归途",
    "en": "Odysseus Homeward (Greece)",
    "country": "Greece",
    "region": "Mediterranean",
    "lat": 37.36,
    "lng": 22.91,
    "category": "Moon",
    "era": "Ancient",
    "summary": "海妖、独眼巨人与忠贞佩涅洛佩，漂泊与身份认同。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "Greece·美杜莎之凝视",
    "en": "Medusa's Gaze (Greece)",
    "country": "Greece",
    "region": "Mediterranean",
    "lat": 37.67,
    "lng": 23.32,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "石化目光与英雄斩首，边界怪物与暴力的反思。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Greece·伊卡洛斯的蜡翼",
    "en": "Icarus and the Wax Wings (Greece)",
    "country": "Greece",
    "region": "Mediterranean",
    "lat": 37.98,
    "lng": 23.73,
    "category": "Sun",
    "era": "Ancient",
    "summary": "飞近太阳坠落，野心与技艺限度的寓言。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Greece·皮格马利翁与雕像",
    "en": "Pygmalion and the Statue (Greece)",
    "country": "Greece",
    "region": "Mediterranean",
    "lat": 38.29,
    "lng": 24.14,
    "category": "Love",
    "era": "Classical",
    "summary": "雕刻获得生命，艺术、欲望与神恩的交织。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Greece·坦塔罗斯的惩罚",
    "en": "Tantalus Punished (Greece)",
    "country": "Greece",
    "region": "Mediterranean",
    "lat": 38.6,
    "lng": 24.55,
    "category": "Flood",
    "era": "Ancient",
    "summary": "触不可及的水与果，后世“折磨”一词来源。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Greece·西西弗斯的巨石",
    "en": "Sisyphus and the Boulder (Greece)",
    "country": "Greece",
    "region": "Mediterranean",
    "lat": 37.36,
    "lng": 22.91,
    "category": "Moon",
    "era": "Ancient",
    "summary": "永劫推石上山，存在主义常引用的希腊原型。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Greece·阿里阿德涅的线团",
    "en": "Ariadne's Thread (Greece)",
    "country": "Greece",
    "region": "Mediterranean",
    "lat": 37.67,
    "lng": 23.32,
    "category": "Love",
    "era": "Ancient",
    "summary": "迷宫救英雄却被遗弃，克里特王女与命运转折。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Greece·金羊毛远征",
    "en": "Quest for the Golden Fleece (Greece)",
    "country": "Greece",
    "region": "Mediterranean",
    "lat": 37.98,
    "lng": 23.73,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "阿尔戈英雄远航科尔喀斯，王权与巫术宝物。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "Greece·赫拉克勒斯的十二试炼",
    "en": "Twelve Labors of Heracles (Greece)",
    "country": "Greece",
    "region": "Mediterranean",
    "lat": 38.29,
    "lng": 24.14,
    "category": "Fire",
    "era": "Ancient",
    "summary": "狮子、九头蛇与冥府犬，文明边界上的怪物谱系。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "India·罗摩衍那",
    "en": "Rama's Journey (India)",
    "country": "India",
    "region": "SouthAsia",
    "lat": 27.98,
    "lng": 76.38,
    "category": "Love",
    "era": "Ancient",
    "summary": "悉多被掳与猴军搭桥，正法与忠诚的史诗核心。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "India·摩诃婆罗多骰局",
    "en": "Dice Game of the Mahabharata (India)",
    "country": "India",
    "region": "SouthAsia",
    "lat": 28.29,
    "lng": 76.79,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "黑公主受辱引发大战，正法与家族宿怨。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "India·奎师那与牛群",
    "en": "Krishna among the Cattle (India)",
    "country": "India",
    "region": "SouthAsia",
    "lat": 28.6,
    "lng": 77.2,
    "category": "Moon",
    "era": "Ancient",
    "summary": "牧童神吹笛与偷奶油，虔敬派情感传统源头。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "India·湿婆之舞",
    "en": "Shiva's Cosmic Dance (India)",
    "country": "India",
    "region": "SouthAsia",
    "lat": 28.91,
    "lng": 77.61,
    "category": "Fire",
    "era": "Ancient",
    "summary": "毁灭与重生在同一舞步，宇宙节律的象征。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "India·恒河女神下凡",
    "en": "Ganga Descends to Earth (India)",
    "country": "India",
    "region": "SouthAsia",
    "lat": 29.22,
    "lng": 78.02,
    "category": "Flood",
    "era": "Ancient",
    "summary": "从天界落为圣河，净化与死亡并置的信仰叙事。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "India·那罗与达摩衍蒂",
    "en": "Nala and Damayanti (India)",
    "country": "India",
    "region": "SouthAsia",
    "lat": 27.98,
    "lng": 76.38,
    "category": "Love",
    "era": "Ancient",
    "summary": "骰子与誓言考验中的王室爱情，命运与诚信。",
    "sourceType": "Epic",
    "confidence": "Medium"
  },
  {
    "cn": "India·搅拌乳海",
    "en": "Churning of the Ocean (India)",
    "country": "India",
    "region": "SouthAsia",
    "lat": 28.29,
    "lng": 76.79,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "神魔共搅甘露，毗湿奴化身与宇宙宝物起源。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "India·杜尔迦斩魔",
    "en": "Durga Slaying Mahishasura (India)",
    "country": "India",
    "region": "SouthAsia",
    "lat": 28.6,
    "lng": 77.2,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "多头女神战胜牛魔，女性力量与节庆来源。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "India·阎摩与冥界",
    "en": "Yama Lord of Death (India)",
    "country": "India",
    "region": "SouthAsia",
    "lat": 28.91,
    "lng": 77.61,
    "category": "Moon",
    "era": "Ancient",
    "summary": "首位死者成为判官，伦理与来世秩序。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "India·舍沙巨蛇",
    "en": "Shesha the World Serpent (India)",
    "country": "India",
    "region": "SouthAsia",
    "lat": 29.22,
    "lng": 78.02,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "千首蛇支撑毗湿奴，时间与宇宙层级。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "India·哈奴曼跨海",
    "en": "Hanuman Leaps the Ocean (India)",
    "country": "India",
    "region": "SouthAsia",
    "lat": 27.98,
    "lng": 76.38,
    "category": "Sun",
    "era": "Ancient",
    "summary": "神猴寻药与焚城，忠诚与勇力的典范。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "India·沙昆塔拉戒指",
    "en": "Shakuntala's Ring (India)",
    "country": "India",
    "region": "SouthAsia",
    "lat": 28.29,
    "lng": 76.79,
    "category": "Love",
    "era": "Ancient",
    "summary": "遗忘咒语与森林女王的团圆，戏剧与记忆主题。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Japan·天照岩户",
    "en": "Amaterasu and the Rock Cave (Japan)",
    "country": "Japan",
    "region": "EastAsia",
    "lat": 35.06,
    "lng": 138.94,
    "category": "Sun",
    "era": "Ancient",
    "summary": "天照躲入天岩户，众神狂欢诱其复出，光与秩序。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Japan·须佐之男命斩八岐",
    "en": "Susanoo and Yamata-no-Orochi (Japan)",
    "country": "Japan",
    "region": "EastAsia",
    "lat": 35.37,
    "lng": 139.35,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "八头蛇与草薙剑，风暴神与出云叙事。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Japan·浦岛太郎",
    "en": "Urashima Tarō (Japan)",
    "country": "Japan",
    "region": "EastAsia",
    "lat": 35.68,
    "lng": 139.76,
    "category": "Love",
    "era": "Folk",
    "summary": "龙宫三日世上千年，时间错位与箱中白烟。",
    "sourceType": "Fairy Tale",
    "confidence": "High"
  },
  {
    "cn": "Japan·桃太郎",
    "en": "Momotarō (Japan)",
    "country": "Japan",
    "region": "EastAsia",
    "lat": 35.99,
    "lng": 140.17,
    "category": "Princess",
    "era": "Folk",
    "summary": "桃中生童子率动物退鬼，民间勇德与团子分享。",
    "sourceType": "Folk Tale",
    "confidence": "High"
  },
  {
    "cn": "Japan·辉夜姬",
    "en": "The Tale of the Bamboo Cutter (Japan)",
    "country": "Japan",
    "region": "EastAsia",
    "lat": 36.3,
    "lng": 140.58,
    "category": "Moon",
    "era": "Classical",
    "summary": "月宫天人下凡，不死与别离的物语文学高峰。",
    "sourceType": "Fairy Tale",
    "confidence": "High"
  },
  {
    "cn": "Japan·一寸法师",
    "en": "Issun-bōshi (Japan)",
    "country": "Japan",
    "region": "EastAsia",
    "lat": 35.06,
    "lng": 138.94,
    "category": "Princess",
    "era": "Folk",
    "summary": "一寸身长娶公主，机智胜过巨体。",
    "sourceType": "Fairy Tale",
    "confidence": "Medium"
  },
  {
    "cn": "Japan·雪女",
    "en": "The Yuki-onna (Japan)",
    "country": "Japan",
    "region": "EastAsia",
    "lat": 35.37,
    "lng": 139.35,
    "category": "Moon",
    "era": "Folk",
    "summary": "山旅人与苍白女妖，誓言与生死边界。",
    "sourceType": "Legend",
    "confidence": "High"
  },
  {
    "cn": "Japan·狐嫁女",
    "en": "The Fox Wedding (Japan)",
    "country": "Japan",
    "region": "EastAsia",
    "lat": 35.68,
    "lng": 139.76,
    "category": "Love",
    "era": "Folk",
    "summary": "晴日雨与狐火婚礼，自然异兆与戏谑。",
    "sourceType": "Folk Tale",
    "confidence": "Medium"
  },
  {
    "cn": "Japan·海坊主",
    "en": "The Umibōzu (Japan)",
    "country": "Japan",
    "region": "EastAsia",
    "lat": 35.99,
    "lng": 140.17,
    "category": "Dragon",
    "era": "Folk",
    "summary": "海上秃头巨怪与船夫问答，海洋恐惧。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Japan·天狗山",
    "en": "Mountain Tengu (Japan)",
    "country": "Japan",
    "region": "EastAsia",
    "lat": 36.3,
    "lng": 140.58,
    "category": "Fire",
    "era": "Folk",
    "summary": "长鼻山僧与剑术传授，傲慢与修行。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Japan·河童与相扑",
    "en": "Kappa and Sumo (Japan)",
    "country": "Japan",
    "region": "EastAsia",
    "lat": 35.06,
    "lng": 138.94,
    "category": "Flood",
    "era": "Folk",
    "summary": "河童挑战人类角力，黄瓜与尻子玉传说。",
    "sourceType": "Folk Tale",
    "confidence": "Low"
  },
  {
    "cn": "Japan·辉夜姬的羽衣",
    "en": "Celestial Robe of Kaguya (Japan)",
    "country": "Japan",
    "region": "EastAsia",
    "lat": 35.37,
    "lng": 139.35,
    "category": "Moon",
    "era": "Classical",
    "summary": "月使取回天衣，凡间记忆消散。",
    "sourceType": "Fairy Tale",
    "confidence": "Medium"
  },
  {
    "cn": "Egypt·拉神日舟",
    "en": "Ra's Solar Barque (Egypt)",
    "country": "Egypt",
    "region": "Mediterranean",
    "lat": 29.42,
    "lng": 30.42,
    "category": "Sun",
    "era": "Ancient",
    "summary": "白昼与冥河夜航，太阳神与混沌蛇阿波菲斯。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Egypt·奥西里斯复活",
    "en": "Resurrection of Osiris (Egypt)",
    "country": "Egypt",
    "region": "Mediterranean",
    "lat": 29.73,
    "lng": 30.83,
    "category": "Love",
    "era": "Ancient",
    "summary": "伊西丝寻尸碎片，冥王与农业循环。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Egypt·荷鲁斯与塞特",
    "en": "Horus and Set (Egypt)",
    "country": "Egypt",
    "region": "Mediterranean",
    "lat": 30.04,
    "lng": 31.24,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "王权之争与受伤之眼，秩序对风暴。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Egypt·伊西丝与七蝎子",
    "en": "Isis and the Seven Scorpions (Egypt)",
    "country": "Egypt",
    "region": "Mediterranean",
    "lat": 30.35,
    "lng": 31.65,
    "category": "Moon",
    "era": "Ancient",
    "summary": "女神护婴与毒蝎誓约，母性与法术。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Egypt·阿努比斯称心",
    "en": "Anubis Weighs the Heart (Egypt)",
    "country": "Egypt",
    "region": "Mediterranean",
    "lat": 30.66,
    "lng": 32.06,
    "category": "Moon",
    "era": "Ancient",
    "summary": "亡魂与玛阿特之羽，伦理审判图像。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Egypt·大洪水传说",
    "en": "Egyptian Flood Lore (Egypt)",
    "country": "Egypt",
    "region": "Mediterranean",
    "lat": 29.42,
    "lng": 30.42,
    "category": "Flood",
    "era": "Ancient",
    "summary": "尼罗河涨落与创世水面叙事变体。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Egypt·贝斯特猫神",
    "en": "Bastet the Cat Goddess (Egypt)",
    "country": "Egypt",
    "region": "Mediterranean",
    "lat": 29.73,
    "lng": 30.83,
    "category": "Princess",
    "era": "Ancient",
    "summary": "家宅保护与节庆狂欢，狮猫二相。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Egypt·托特书吏",
    "en": "Thoth the Scribe (Egypt)",
    "country": "Egypt",
    "region": "Mediterranean",
    "lat": 30.04,
    "lng": 31.24,
    "category": "Moon",
    "era": "Ancient",
    "summary": "月亮与文字之神，智慧仲裁。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Egypt·斯芬克斯谜语",
    "en": "Riddle of the Sphinx (Egypt)",
    "country": "Egypt",
    "region": "Mediterranean",
    "lat": 30.35,
    "lng": 31.65,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "人狮怪物与俄狄浦斯式命运（埃及变体流传）。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Egypt·杜阿特十二夜",
    "en": "Twelve Hours of the Duat (Egypt)",
    "country": "Egypt",
    "region": "Mediterranean",
    "lat": 30.66,
    "lng": 32.06,
    "category": "Fire",
    "era": "Ancient",
    "summary": "冥界夜航十二域门，太阳船与守护蛇。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "United Kingdom·亚瑟与石中剑",
    "en": "Arthur and the Sword in the Stone (United Kingdom)",
    "country": "United Kingdom",
    "region": "NordicCeltic",
    "lat": 50.88,
    "lng": -0.94,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "王权神授与圆桌骑士传统的核心意象。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "United Kingdom·湖中女士",
    "en": "The Lady of the Lake (United Kingdom)",
    "country": "United Kingdom",
    "region": "NordicCeltic",
    "lat": 51.19,
    "lng": -0.53,
    "category": "Moon",
    "era": "Medieval",
    "summary": "赠剑与收回，神秘水域与君主合法性。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "United Kingdom·高文与绿骑士",
    "en": "Gawain and the Green Knight (United Kingdom)",
    "country": "United Kingdom",
    "region": "NordicCeltic",
    "lat": 51.5,
    "lng": -0.12,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "斩首游戏与诚信考验，圣诞与荒野。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "United Kingdom·贝奥武夫与海怪",
    "en": "Beowulf and Sea Monsters (United Kingdom)",
    "country": "United Kingdom",
    "region": "NordicCeltic",
    "lat": 51.81,
    "lng": 0.29,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "大厅英雄与格伦德尔，盎格鲁-撒克逊史诗。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "United Kingdom·塔列辛与变形",
    "en": "Taliesin and Shapeshifting (United Kingdom)",
    "country": "United Kingdom",
    "region": "NordicCeltic",
    "lat": 52.12,
    "lng": 0.7,
    "category": "Moon",
    "era": "Medieval",
    "summary": "威尔士诗人变形与智慧竞赛。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "United Kingdom·罗宾汉舍伍德",
    "en": "Robin Hood of Sherwood (United Kingdom)",
    "country": "United Kingdom",
    "region": "NordicCeltic",
    "lat": 50.88,
    "lng": -0.94,
    "category": "Love",
    "era": "Medieval",
    "summary": "劫富济贫与诺丁汉郡长，绿林正义。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "United Kingdom·杰克与豆茎",
    "en": "Jack and the Beanstalk (United Kingdom)",
    "country": "United Kingdom",
    "region": "NordicCeltic",
    "lat": 51.19,
    "lng": -0.53,
    "category": "Princess",
    "era": "Folk",
    "summary": "巨人国金蛋与魔豆，英语童话经典。",
    "sourceType": "Fairy Tale",
    "confidence": "High"
  },
  {
    "cn": "United Kingdom·灰姑娘变体",
    "en": "Cinderella Variant (Britain) (United Kingdom)",
    "country": "United Kingdom",
    "region": "NordicCeltic",
    "lat": 51.5,
    "lng": -0.12,
    "category": "Princess",
    "era": "Folk",
    "summary": "榛树与鸟助，玻璃鞋舞会。",
    "sourceType": "Fairy Tale",
    "confidence": "High"
  },
  {
    "cn": "United Kingdom·潘德拉根血脉",
    "en": "Bloodline of Pendragon (United Kingdom)",
    "country": "United Kingdom",
    "region": "NordicCeltic",
    "lat": 51.81,
    "lng": 0.29,
    "category": "Fire",
    "era": "Medieval",
    "summary": "红龙与白龙预言，凯尔特王权神话。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "United Kingdom·伦敦塔渡鸦",
    "en": "Ravens of the Tower (United Kingdom)",
    "country": "United Kingdom",
    "region": "NordicCeltic",
    "lat": 52.12,
    "lng": 0.7,
    "category": "Moon",
    "era": "Folk",
    "summary": "渡鸦离去则王国陨落，现代民俗与国家象征。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Ireland·图阿萨·代·达南",
    "en": "Tuatha Dé Danann (Ireland)",
    "country": "Ireland",
    "region": "NordicCeltic",
    "lat": 52.73,
    "lng": -7.08,
    "category": "Moon",
    "era": "Ancient",
    "summary": "神族与地下城仙丘，爱尔兰神话主干。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Ireland·库丘林狂战",
    "en": "Cú Chulainn's Warp-Spasm (Ireland)",
    "country": "Ireland",
    "region": "NordicCeltic",
    "lat": 53.04,
    "lng": -6.67,
    "category": "Fire",
    "era": "Ancient",
    "summary": "少年英雄守境与 géis 禁忌，阿尔斯特史诗。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "Ireland·李尔的孩子们",
    "en": "Children of Lir (Ireland)",
    "country": "Ireland",
    "region": "NordicCeltic",
    "lat": 53.35,
    "lng": -6.26,
    "category": "Love",
    "era": "Ancient",
    "summary": "继母将四子变天鹅九百年，悲情与天鹅湖母题。",
    "sourceType": "Legend",
    "confidence": "High"
  },
  {
    "cn": "Ireland·芬恩与鲑鱼智慧",
    "en": "Fionn and the Salmon of Knowledge (Ireland)",
    "country": "Ireland",
    "region": "NordicCeltic",
    "lat": 53.66,
    "lng": -5.85,
    "category": "Moon",
    "era": "Ancient",
    "summary": "拇指尝到智慧鲑，诗人勇士传统。",
    "sourceType": "Legend",
    "confidence": "High"
  },
  {
    "cn": "Ireland·报丧女妖",
    "en": "The Banshee (Ireland)",
    "country": "Ireland",
    "region": "NordicCeltic",
    "lat": 53.97,
    "lng": -5.44,
    "category": "Moon",
    "era": "Folk",
    "summary": "家族死亡预兆的哀泣精灵，口传恐惧。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Ireland·小矮妖与金罐",
    "en": "Leprechaun's Gold (Ireland)",
    "country": "Ireland",
    "region": "NordicCeltic",
    "lat": 52.73,
    "lng": -7.08,
    "category": "Princess",
    "era": "Folk",
    "summary": "彩虹尽头金罐与绿衣鞋匠，机智与陷阱。",
    "sourceType": "Folk Tale",
    "confidence": "Medium"
  },
  {
    "cn": "Ireland·奥伊辛地底国",
    "en": "Oisín in Tír na nÓg (Ireland)",
    "country": "Ireland",
    "region": "NordicCeltic",
    "lat": 53.04,
    "lng": -6.67,
    "category": "Love",
    "era": "Ancient",
    "summary": "仙国一日人间百年，返乡衰老。",
    "sourceType": "Legend",
    "confidence": "High"
  },
  {
    "cn": "Ireland·圣帕特里克驱蛇",
    "en": "Patrick and the Serpents (Ireland)",
    "country": "Ireland",
    "region": "NordicCeltic",
    "lat": 53.35,
    "lng": -6.26,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "基督教化叙事与蛇象征，争议性民间解释。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Norway·诸神黄昏",
    "en": "Ragnarök (Norway)",
    "country": "Norway",
    "region": "NordicCeltic",
    "lat": 59.29,
    "lng": 9.93,
    "category": "Fire",
    "era": "Ancient",
    "summary": "巨狼、世界蛇与苏尔特烈焰，北欧终末。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Norway·雷神之锤",
    "en": "Thor's Mjölnir (Norway)",
    "country": "Norway",
    "region": "NordicCeltic",
    "lat": 59.6,
    "lng": 10.34,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "侏儒锻造与巨人试炼，雷电与保护。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Norway·巴德尔之死",
    "en": "Death of Baldr (Norway)",
    "country": "Norway",
    "region": "NordicCeltic",
    "lat": 59.91,
    "lng": 10.75,
    "category": "Love",
    "era": "Ancient",
    "summary": "槲寄生与洛基诡计，光明陨落与冥界谈判。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Norway·女武神之选",
    "en": "Valkyrie's Choice (Norway)",
    "country": "Norway",
    "region": "NordicCeltic",
    "lat": 60.22,
    "lng": 11.16,
    "category": "Princess",
    "era": "Ancient",
    "summary": "战场英灵入瓦尔哈拉，死亡与荣耀。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Norway·耶梦加得环绕中庭",
    "en": "Jörmungandr Encircles Midgard (Norway)",
    "country": "Norway",
    "region": "NordicCeltic",
    "lat": 60.53,
    "lng": 11.57,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "世界蛇与托尔 fishing 终局。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Norway·西格德屠龙",
    "en": "Sigurd and Fafnir (Norway)",
    "country": "Norway",
    "region": "NordicCeltic",
    "lat": 59.29,
    "lng": 9.93,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "龙血听懂鸟语，尼伯龙根链条。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "Norway·海拉冥国",
    "en": "Hel and Her Realm (Norway)",
    "country": "Norway",
    "region": "NordicCeltic",
    "lat": 59.6,
    "lng": 10.34,
    "category": "Moon",
    "era": "Ancient",
    "summary": "半面蓝肤冥后，非罪者之死所。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Iran·阿胡拉·马兹达之光",
    "en": "Light of Ahura Mazda (Iran)",
    "country": "Iran",
    "region": "PersiaArabia",
    "lat": 35.07,
    "lng": 50.57,
    "category": "Sun",
    "era": "Ancient",
    "summary": "善恶二元宇宙观，光明主神与真理。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Iran·鲁斯塔姆与白象",
    "en": "Rostam and the White Elephant (Iran)",
    "country": "Iran",
    "region": "PersiaArabia",
    "lat": 35.38,
    "lng": 50.98,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "波斯史诗英雄试炼与父子悲剧伏笔。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "Iran·西摩格鸟",
    "en": "Simorgh the Great Bird (Iran)",
    "country": "Iran",
    "region": "PersiaArabia",
    "lat": 35.69,
    "lng": 51.39,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "羽翼疗伤与智慧，民族史诗意象。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Iran·查哈克肩蛇",
    "en": "Zahhak and the Serpents (Iran)",
    "country": "Iran",
    "region": "PersiaArabia",
    "lat": 36,
    "lng": 51.8,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "双肩蛇与厨子费雷敦，暴政与解放。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Iran·七试七袍",
    "en": "Seven Trials of Esfandiyār (Iran)",
    "country": "Iran",
    "region": "PersiaArabia",
    "lat": 36.31,
    "lng": 52.21,
    "category": "Fire",
    "era": "Ancient",
    "summary": "铜身英雄与不可杀之咒，王权嫉妒。",
    "sourceType": "Epic",
    "confidence": "Medium"
  },
  {
    "cn": "Iran·阿维斯陀洪水",
    "en": "Avestan Deluge Lore (Iran)",
    "country": "Iran",
    "region": "PersiaArabia",
    "lat": 35.07,
    "lng": 50.57,
    "category": "Flood",
    "era": "Ancient",
    "summary": "方舟与牲畜种子，洪灾与重建。",
    "sourceType": "Myth",
    "confidence": "Low"
  },
  {
    "cn": "Iran·密特拉祭",
    "en": "Mithraic Mysteries (Iran)",
    "country": "Iran",
    "region": "PersiaArabia",
    "lat": 35.38,
    "lng": 50.98,
    "category": "Sun",
    "era": "Ancient",
    "summary": "地下密仪与屠牛图，太阳契约神。",
    "sourceType": "Myth",
    "confidence": "Low"
  },
  {
    "cn": "Iraq·吉尔伽美什与恩奇都",
    "en": "Gilgamesh and Enkidu (Iraq)",
    "country": "Iraq",
    "region": "PersiaArabia",
    "lat": 32.69,
    "lng": 43.55,
    "category": "Love",
    "era": "Ancient",
    "summary": "野人进城与冥府之旅，最早史诗之一。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "Iraq·大洪水泥板",
    "en": "Flood Tablet of Utnapishtim (Iraq)",
    "country": "Iraq",
    "region": "PersiaArabia",
    "lat": 33,
    "lng": 43.96,
    "category": "Flood",
    "era": "Ancient",
    "summary": "方舟与鸽子，与后世洪水叙事互文。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Iraq·伊南娜下冥界",
    "en": "Inanna's Descent (Iraq)",
    "country": "Iraq",
    "region": "PersiaArabia",
    "lat": 33.31,
    "lng": 44.37,
    "category": "Moon",
    "era": "Ancient",
    "summary": "七道门剥衣与死而复生，苏美尔女王神。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Iraq·马尔杜克斩提亚马特",
    "en": "Marduk Slaying Tiamat (Iraq)",
    "country": "Iraq",
    "region": "PersiaArabia",
    "lat": 33.62,
    "lng": 44.78,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "咸水龙尸化天地，巴比伦城神上升。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Iraq·埃塔纳骑鹰",
    "en": "Etana and the Eagle (Iraq)",
    "country": "Iraq",
    "region": "PersiaArabia",
    "lat": 33.93,
    "lng": 45.19,
    "category": "Sun",
    "era": "Ancient",
    "summary": "求子王与鹰上天庭，王权与神药。",
    "sourceType": "Myth",
    "confidence": "Low"
  },
  {
    "cn": "Iraq·乌尔南模与洪水",
    "en": "Ur-Nammu Flood Lore (Iraq)",
    "country": "Iraq",
    "region": "PersiaArabia",
    "lat": 32.69,
    "lng": 43.55,
    "category": "Flood",
    "era": "Ancient",
    "summary": "苏美尔王表与灾变记忆。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Iraq·吉尔伽美什拒不死草",
    "en": "Gilgamesh Loses the Plant (Iraq)",
    "country": "Iraq",
    "region": "PersiaArabia",
    "lat": 33,
    "lng": 43.96,
    "category": "Moon",
    "era": "Ancient",
    "summary": "蛇偷返老草， mortality 的沉思。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "Mexico·羽蛇神创世",
    "en": "Quetzalcoatl Creation (Mexico)",
    "country": "Mexico",
    "region": "Americas",
    "lat": 18.81,
    "lng": -99.95,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "风与晨星之神参与第五太阳纪。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Mexico·第五太阳纪",
    "en": "Fifth Sun Era (Mexico)",
    "country": "Mexico",
    "region": "Americas",
    "lat": 19.12,
    "lng": -99.54,
    "category": "Sun",
    "era": "Ancient",
    "summary": "众神自焚化日，心脏献祭与宇宙更新。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Mexico·阿兹特克冥界九夜",
    "en": "Nine Nights of Mictlan (Mexico)",
    "country": "Mexico",
    "region": "Americas",
    "lat": 19.43,
    "lng": -99.13,
    "category": "Moon",
    "era": "Ancient",
    "summary": "亡灵穿越九层冥府，狗伴与骨镜。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Mexico·波波卡特佩特恋人峰",
    "en": "Popocatépetl Lovers (Mexico)",
    "country": "Mexico",
    "region": "Americas",
    "lat": 19.74,
    "lng": -98.72,
    "category": "Love",
    "era": "Folk",
    "summary": "战士与公主化火山，墨西哥城传说。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Mexico·修洛特尔与狗",
    "en": "Xolotl and the Dog (Mexico)",
    "country": "Mexico",
    "region": "Americas",
    "lat": 20.05,
    "lng": -98.31,
    "category": "Moon",
    "era": "Ancient",
    "summary": "双生神引导亡灵，畸形与金星。",
    "sourceType": "Myth",
    "confidence": "Low"
  },
  {
    "cn": "Mexico·玉米神重生",
    "en": "Maize God Resurrection (Mexico)",
    "country": "Mexico",
    "region": "Americas",
    "lat": 18.81,
    "lng": -99.95,
    "category": "Sun",
    "era": "Ancient",
    "summary": "地下剖分与再长，农业宇宙观。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Mexico·奇奇米克人南迁",
    "en": "Chichimec Migration Lore (Mexico)",
    "country": "Mexico",
    "region": "Americas",
    "lat": 19.12,
    "lng": -99.54,
    "category": "Flood",
    "era": "Medieval",
    "summary": "沙漠部族与谷地文明相遇的口述史。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Peru·维拉科查跨海",
    "en": "Viracocha across the Sea (Peru)",
    "country": "Peru",
    "region": "Americas",
    "lat": -12.67,
    "lng": -77.86,
    "category": "Sun",
    "era": "Ancient",
    "summary": "造物神行化流浪者，安第斯文明主神。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Peru·印加起源双兄弟",
    "en": "Manco Capac Legend (Peru)",
    "country": "Peru",
    "region": "Americas",
    "lat": -12.36,
    "lng": -77.45,
    "category": "Love",
    "era": "Ancient",
    "summary": "太阳子女携金杖寻谷地建都。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Peru·阿普山灵",
    "en": "Apu Mountain Spirits (Peru)",
    "country": "Peru",
    "region": "Americas",
    "lat": -12.05,
    "lng": -77.04,
    "category": "Moon",
    "era": "Folk",
    "summary": "峰峦有灵，登山祭与雪崩解释。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Peru·帕查玛玛大地母",
    "en": "Pachamama Earth Mother (Peru)",
    "country": "Peru",
    "region": "Americas",
    "lat": -11.74,
    "lng": -76.63,
    "category": "Love",
    "era": "Folk",
    "summary": "大地祭与 Coca 仪礼，生态伦理。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Peru·印加绳结史",
    "en": "Quipu Memory Lore (Peru)",
    "country": "Peru",
    "region": "Americas",
    "lat": -11.43,
    "lng": -76.22,
    "category": "Princess",
    "era": "Medieval",
    "summary": "结绳记事与口述史诗并行。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Peru·的的喀喀湖起源",
    "en": "Lake Titicaca Origin (Peru)",
    "country": "Peru",
    "region": "Americas",
    "lat": -12.67,
    "lng": -77.86,
    "category": "Flood",
    "era": "Ancient",
    "summary": "太阳岛与第一对夫妇上岸。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "United States·雷鸟与鲸",
    "en": "Thunderbird and Whale (United States)",
    "country": "United States",
    "region": "Americas",
    "lat": 39.18,
    "lng": -99.4,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "太平洋西北海岸巨鸟与海中巨兽之战。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "United States·蜘蛛女造人",
    "en": "Spider Grandmother (United States)",
    "country": "United States",
    "region": "Americas",
    "lat": 39.49,
    "lng": -98.99,
    "category": "Moon",
    "era": "Ancient",
    "summary": "纳瓦霍等族创世与纺织智慧。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "United States·郊狼诡计",
    "en": "Coyote the Trickster (United States)",
    "country": "United States",
    "region": "Americas",
    "lat": 39.8,
    "lng": -98.58,
    "category": "Love",
    "era": "Folk",
    "summary": "平原与西南广泛流传的狡黠与教训。",
    "sourceType": "Folk Tale",
    "confidence": "High"
  },
  {
    "cn": "United States·易洛魁长屋和平",
    "en": "Great Peacemaker (United States)",
    "country": "United States",
    "region": "Americas",
    "lat": 40.11,
    "lng": -98.17,
    "category": "Princess",
    "era": "Ancient",
    "summary": "五族联盟与埋武器，口述宪法叙事。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "United States·鬼舞与归来",
    "en": "Ghost Dance Vision (United States)",
    "country": "United States",
    "region": "Americas",
    "lat": 40.42,
    "lng": -97.76,
    "category": "Moon",
    "era": "Folk",
    "summary": "19 世纪平原复兴运动中的末世期盼。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "United States·双子英雄",
    "en": "Hero Twins (United States)",
    "country": "United States",
    "region": "Americas",
    "lat": 39.18,
    "lng": -99.4,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "球赛下冥界，玛雅叙事在北美接触带传播变体。",
    "sourceType": "Myth",
    "confidence": "Low"
  },
  {
    "cn": "Russia·芭芭雅嘎小屋",
    "en": "Baba Yaga's Hut (Russia)",
    "country": "Russia",
    "region": "SlavicBalkan",
    "lat": 55.13,
    "lng": 36.8,
    "category": "Moon",
    "era": "Folk",
    "summary": "鸡腿骨屋与森林女巫，考验与边界。",
    "sourceType": "Fairy Tale",
    "confidence": "High"
  },
  {
    "cn": "Russia·火鸟与金苹果",
    "en": "Firebird and Golden Apples (Russia)",
    "country": "Russia",
    "region": "SlavicBalkan",
    "lat": 55.44,
    "lng": 37.21,
    "category": "Princess",
    "era": "Folk",
    "summary": "三王子追神鸟，俄国童话高峰。",
    "sourceType": "Fairy Tale",
    "confidence": "High"
  },
  {
    "cn": "Russia·鲁斯兰与鹰头狮",
    "en": "Ruslan and the Head (Russia)",
    "country": "Russia",
    "region": "SlavicBalkan",
    "lat": 55.75,
    "lng": 37.62,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "长须英雄救妻与魔法头颅。",
    "sourceType": "Epic",
    "confidence": "Medium"
  },
  {
    "cn": "Russia·冬王与雪姑娘",
    "en": "Morozko and Snegurochka (Russia)",
    "country": "Russia",
    "region": "SlavicBalkan",
    "lat": 56.06,
    "lng": 38.03,
    "category": "Moon",
    "era": "Folk",
    "summary": "冻父考验继女，冰雪精灵。",
    "sourceType": "Fairy Tale",
    "confidence": "High"
  },
  {
    "cn": "Russia·沃加河水怪",
    "en": "Vodyanoy of the River (Russia)",
    "country": "Russia",
    "region": "SlavicBalkan",
    "lat": 56.37,
    "lng": 38.44,
    "category": "Flood",
    "era": "Folk",
    "summary": "水妖拖人入河，磨坊与禁忌。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Russia·多布雷尼亚屠龙",
    "en": "Dobrynya and the Dragon (Russia)",
    "country": "Russia",
    "region": "SlavicBalkan",
    "lat": 55.13,
    "lng": 36.8,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "基辅罗斯勇士叙事。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Germany·尼伯龙根之歌",
    "en": "Song of the Nibelung (Germany)",
    "country": "Germany",
    "region": "CentralEurope",
    "lat": 51.9,
    "lng": 12.585,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "宝藏、背叛与屠龙，德语史诗核心。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "Germany·格林童话·汉泽尔与格莱特",
    "en": "Hansel and Gretel (Germany)",
    "country": "Germany",
    "region": "CentralEurope",
    "lat": 52.21,
    "lng": 12.995,
    "category": "Princess",
    "era": "Folk",
    "summary": "面包屑与糖果屋，森林弃儿。",
    "sourceType": "Fairy Tale",
    "confidence": "High"
  },
  {
    "cn": "Germany·格林童话·白雪公主",
    "en": "Snow White (Germany)",
    "country": "Germany",
    "region": "CentralEurope",
    "lat": 52.52,
    "lng": 13.405,
    "category": "Princess",
    "era": "Folk",
    "summary": "魔镜与七矮人，毒苹果。",
    "sourceType": "Fairy Tale",
    "confidence": "High"
  },
  {
    "cn": "Germany·罗累莱礁石",
    "en": "Lorelei Rock (Germany)",
    "country": "Germany",
    "region": "CentralEurope",
    "lat": 52.83,
    "lng": 13.815,
    "category": "Love",
    "era": "Folk",
    "summary": "莱茵女妖歌声诱船沉没。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Germany·浮士德契约",
    "en": "Faustian Bargain (Germany)",
    "country": "Germany",
    "region": "CentralEurope",
    "lat": 53.14,
    "lng": 14.225,
    "category": "Fire",
    "era": "Medieval",
    "summary": "学者与魔鬼，知识与灵魂的交换。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Germany·瓦尔普吉斯之夜",
    "en": "Walpurgis Night (Germany)",
    "country": "Germany",
    "region": "CentralEurope",
    "lat": 51.9,
    "lng": 12.585,
    "category": "Moon",
    "era": "Folk",
    "summary": "布罗肯峰魔女集会，春至与恐惧。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "France·罗兰之歌",
    "en": "Song of Roland (France)",
    "country": "France",
    "region": "WesternEurope",
    "lat": 48.24,
    "lng": 1.53,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "奥利凡特号角与查理曼后卫，史诗忠诚。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "France·贝狄福尔圣杯",
    "en": "Percival and the Grail (France)",
    "country": "France",
    "region": "WesternEurope",
    "lat": 48.55,
    "lng": 1.94,
    "category": "Moon",
    "era": "Medieval",
    "summary": "法兰西亚瑟圈变体，圣杯追寻。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "France·蓝胡子",
    "en": "Bluebeard (France)",
    "country": "France",
    "region": "WesternEurope",
    "lat": 48.86,
    "lng": 2.35,
    "category": "Princess",
    "era": "Folk",
    "summary": "禁忌房间与姊妹救赎，佩罗童话。",
    "sourceType": "Fairy Tale",
    "confidence": "High"
  },
  {
    "cn": "France·穿靴子的猫",
    "en": "Puss in Boots (France)",
    "country": "France",
    "region": "WesternEurope",
    "lat": 49.17,
    "lng": 2.76,
    "category": "Princess",
    "era": "Folk",
    "summary": "猫为主人骗得城堡与公主。",
    "sourceType": "Fairy Tale",
    "confidence": "High"
  },
  {
    "cn": "France·美女与野兽",
    "en": "Beauty and the Beast (France)",
    "country": "France",
    "region": "WesternEurope",
    "lat": 49.48,
    "lng": 3.17,
    "category": "Love",
    "era": "Folk",
    "summary": "变形与同情，洛可可时期定型。",
    "sourceType": "Fairy Tale",
    "confidence": "High"
  },
  {
    "cn": "France·梅绿丝河仙",
    "en": "Melusine of Lusignan (France)",
    "country": "France",
    "region": "WesternEurope",
    "lat": 48.24,
    "lng": 1.53,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "半蛇女建城与沐浴禁忌。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Italy·埃涅阿斯纪",
    "en": "Aeneas' Journey (Italy)",
    "country": "Italy",
    "region": "Mediterranean",
    "lat": 41.28,
    "lng": 11.67,
    "category": "Love",
    "era": "Ancient",
    "summary": "特洛伊遗民建罗马，命运与虔敬。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "Italy·罗慕路斯与雷穆斯",
    "en": "Romulus and Remus (Italy)",
    "country": "Italy",
    "region": "Mediterranean",
    "lat": 41.59,
    "lng": 12.08,
    "category": "Moon",
    "era": "Ancient",
    "summary": "母狼哺婴与兄弟墙杀，建城神话。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Italy·塔奎因与卢克蕾提亚",
    "en": "Tarquin and Lucretia (Italy)",
    "country": "Italy",
    "region": "Mediterranean",
    "lat": 41.9,
    "lng": 12.49,
    "category": "Love",
    "era": "Ancient",
    "summary": "暴行引发共和革命，政治伦理叙事。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Italy·贝芬特与五朔节",
    "en": "Befana Epiphany (Italy)",
    "country": "Italy",
    "region": "Mediterranean",
    "lat": 42.21,
    "lng": 12.9,
    "category": "Princess",
    "era": "Folk",
    "summary": "老妇扫尘赠糖，主显节民俗。",
    "sourceType": "Folk Tale",
    "confidence": "Medium"
  },
  {
    "cn": "Italy·西西里独眼巨人",
    "en": "Cyclops in Sicily (Italy)",
    "country": "Italy",
    "region": "Mediterranean",
    "lat": 42.52,
    "lng": 13.31,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "奥德修斯盲波吕斐摩斯的地方记忆。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Australia·梦时代蛇祖",
    "en": "Rainbow Serpent Dreaming (Australia)",
    "country": "Australia",
    "region": "Oceania",
    "lat": -25.89,
    "lng": 132.96,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "塑造河道与律法，广泛分布于澳洲原住民宇宙观。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Australia·塔纳米创生",
    "en": "Tarnami Creation (Australia)",
    "country": "Australia",
    "region": "Oceania",
    "lat": -25.58,
    "lng": 133.37,
    "category": "Sun",
    "era": "Ancient",
    "summary": "祖先行歌画地貌，仪式与地理合一。",
    "sourceType": "Myth",
    "confidence": "Low"
  },
  {
    "cn": "Australia·七姊妹星团",
    "en": "Pleiades Seven Sisters (Australia)",
    "country": "Australia",
    "region": "Oceania",
    "lat": -25.27,
    "lng": 133.78,
    "category": "Moon",
    "era": "Ancient",
    "summary": "追逐与升空，跨部族星神话。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Australia·袋狼人与边界",
    "en": "Bunyip Waters (Australia)",
    "country": "Australia",
    "region": "Oceania",
    "lat": -24.96,
    "lng": 134.19,
    "category": "Flood",
    "era": "Folk",
    "summary": "沼泽怪兽与儿童禁忌，殖民前后层叠叙事。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Australia·火棍窃火",
    "en": "Fire Theft Lore (Australia)",
    "country": "Australia",
    "region": "Oceania",
    "lat": -24.65,
    "lng": 134.6,
    "category": "Fire",
    "era": "Ancient",
    "summary": "鸟或蜥蜴盗火给人类，区域变体。",
    "sourceType": "Myth",
    "confidence": "Low"
  },
  {
    "cn": "Nigeria·奥巴塔拉造人",
    "en": "Obatala Shapes Humanity (Nigeria)",
    "country": "Nigeria",
    "region": "Africa",
    "lat": 5.9,
    "lng": 2.56,
    "category": "Moon",
    "era": "Ancient",
    "summary": "约鲁巴至高神与泥塑人形。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Nigeria·舒舒波纳里河灵",
    "en": "Shokpona River Ordeal (Nigeria)",
    "country": "Nigeria",
    "region": "Africa",
    "lat": 6.21,
    "lng": 2.97,
    "category": "Flood",
    "era": "Folk",
    "summary": "天花与河祭，伦理与恐惧。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Nigeria·乌龟与鸟赛跑",
    "en": "Tortoise and Birds (Nigeria)",
    "country": "Nigeria",
    "region": "Africa",
    "lat": 6.52,
    "lng": 3.38,
    "category": "Love",
    "era": "Folk",
    "summary": "阿南西式狡诈故事在尼日利亚变体。",
    "sourceType": "Folk Tale",
    "confidence": "High"
  },
  {
    "cn": "Nigeria·埃苏与十字路口",
    "en": "Esu at the Crossroads (Nigeria)",
    "country": "Nigeria",
    "region": "Africa",
    "lat": 6.83,
    "lng": 3.79,
    "category": "Moon",
    "era": "Ancient",
    "summary": " trickster 与选择，约鲁巴-巴西 diaspora。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Ghana·阿南西与智慧罐",
    "en": "Anansi and the Pot of Wisdom (Ghana)",
    "country": "Ghana",
    "region": "Africa",
    "lat": 4.98,
    "lng": -1.01,
    "category": "Moon",
    "era": "Folk",
    "summary": "蜘蛛集故事又散落人间，阿坎传统。",
    "sourceType": "Folk Tale",
    "confidence": "High"
  },
  {
    "cn": "Ghana·金凳子降临",
    "en": "Golden Stool Descent (Ghana)",
    "country": "Ghana",
    "region": "Africa",
    "lat": 5.29,
    "lng": -0.6,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "阿散蒂王权天授物，政治神话。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Ghana·河神新娘",
    "en": "River Bride Lore (Ghana)",
    "country": "Ghana",
    "region": "Africa",
    "lat": 5.6,
    "lng": -0.19,
    "category": "Love",
    "era": "Folk",
    "summary": "沃尔特河流域献祭与婚配叙事。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Ghana·猎人阿塔",
    "en": "Ataa the Hunter (Ghana)",
    "country": "Ghana",
    "region": "Africa",
    "lat": 5.91,
    "lng": 0.22,
    "category": "Fire",
    "era": "Folk",
    "summary": "森林精怪与禁忌肉，口传教训。",
    "sourceType": "Folk Tale",
    "confidence": "Medium"
  },
  {
    "cn": "Kenya·基库尤九女",
    "en": "Nine Daughters of Mumbi (Kenya)",
    "country": "Kenya",
    "region": "Africa",
    "lat": -1.91,
    "lng": 36,
    "category": "Princess",
    "era": "Ancient",
    "summary": "基库尤部族起源与氏族分配。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Kenya·奈伊恩盖与彩虹",
    "en": "Ngai on Mount Kenya (Kenya)",
    "country": "Kenya",
    "region": "Africa",
    "lat": -1.6,
    "lng": 36.41,
    "category": "Sun",
    "era": "Ancient",
    "summary": "至高神居山巅，雷与雨。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Kenya·鬣狗与月亮",
    "en": "Hyena and the Moon (Kenya)",
    "country": "Kenya",
    "region": "Africa",
    "lat": -1.29,
    "lng": 36.82,
    "category": "Moon",
    "era": "Folk",
    "summary": "月相与动物性格寓言。",
    "sourceType": "Folk Tale",
    "confidence": "Low"
  },
  {
    "cn": "Kenya·马赛狮子战士",
    "en": "Maasai and the Lion (Kenya)",
    "country": "Kenya",
    "region": "Africa",
    "lat": -0.98,
    "lng": 37.23,
    "category": "Dragon",
    "era": "Folk",
    "summary": "成人礼与草原伦理。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Ethiopia·示巴女王觐见",
    "en": "Queen of Sheba's Visit (Ethiopia)",
    "country": "Ethiopia",
    "region": "Africa",
    "lat": 8.41,
    "lng": 37.93,
    "category": "Love",
    "era": "Ancient",
    "summary": "所罗门智慧与埃塞俄比亚王统系谱。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Ethiopia·基布克斯与十字架",
    "en": "Kebra Nagast Lore (Ethiopia)",
    "country": "Ethiopia",
    "region": "Africa",
    "lat": 8.72,
    "lng": 38.34,
    "category": "Sun",
    "era": "Medieval",
    "summary": "约柜南迁叙事，国族宗教文本。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Ethiopia·阿比西尼亚龙",
    "en": "Ethiopian Dragon Lore (Ethiopia)",
    "country": "Ethiopia",
    "region": "Africa",
    "lat": 9.03,
    "lng": 38.75,
    "category": "Dragon",
    "era": "Folk",
    "summary": "高原基督教与本土怪兽融合。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Ethiopia·尼罗河源少女",
    "en": "Source of the Nile Maiden (Ethiopia)",
    "country": "Ethiopia",
    "region": "Africa",
    "lat": 9.34,
    "lng": 39.16,
    "category": "Flood",
    "era": "Folk",
    "summary": "青尼罗河民间解释。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "South Africa·乌纳米库鲁鸟",
    "en": "Unkulunkulu Creation (South Africa)",
    "country": "South Africa",
    "region": "Africa",
    "lat": -26.82,
    "lng": 27.22,
    "category": "Sun",
    "era": "Ancient",
    "summary": "祖鲁创世祖与第一人。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "South Africa·托伊托伊英雄",
    "en": "Toyi-toyi Heroes (South Africa)",
    "country": "South Africa",
    "region": "Africa",
    "lat": -26.51,
    "lng": 27.63,
    "category": "Fire",
    "era": "Folk",
    "summary": "当代抗争歌谣与灵物叙事叠合。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "South Africa·水兔与月亮",
    "en": "Water Hare and Moon (South Africa)",
    "country": "South Africa",
    "region": "Africa",
    "lat": -26.2,
    "lng": 28.04,
    "category": "Moon",
    "era": "Folk",
    "summary": "桑与科伊桑圈动物寓言。",
    "sourceType": "Folk Tale",
    "confidence": "Low"
  },
  {
    "cn": "South Africa·闪电鸟",
    "en": "Lightning Bird Lore (South Africa)",
    "country": "South Africa",
    "region": "Africa",
    "lat": -25.89,
    "lng": 28.45,
    "category": "Dragon",
    "era": "Folk",
    "summary": "招雷与巫术，东南部班图传统。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Korea·檀君朝鲜",
    "en": "Dangun Wanggeom (Korea)",
    "country": "Korea",
    "region": "EastAsia",
    "lat": 36.95,
    "lng": 126.16,
    "category": "Sun",
    "era": "Ancient",
    "summary": "熊女与檀君建国，半岛起源神话。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Korea·沈清传孝女",
    "en": "Shim Cheong Filial Tale (Korea)",
    "country": "Korea",
    "region": "EastAsia",
    "lat": 37.26,
    "lng": 126.57,
    "category": "Love",
    "era": "Medieval",
    "summary": "盲父与献祭龙王，孝女叙事。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Taiwan·阿里山邹族祭典",
    "en": "Tsou War Ritual (Taiwan)",
    "country": "Taiwan",
    "region": "EastAsia",
    "lat": 23.08,
    "lng": 120.18,
    "category": "Fire",
    "era": "Folk",
    "summary": "战祭与 MAYASVI，原住民宇宙秩序。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Taiwan·妈祖渡海",
    "en": "Mazu Crosses the Sea (Taiwan)",
    "country": "Taiwan",
    "region": "EastAsia",
    "lat": 23.39,
    "lng": 120.59,
    "category": "Flood",
    "era": "Medieval",
    "summary": "海上女神信仰，闽南文化圈代表。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Pakistan·希德尔与里尔",
    "en": "Heer Ranjha (Pakistan)",
    "country": "Pakistan",
    "region": "SouthAsia",
    "lat": 33.06,
    "lng": 72.23,
    "category": "Love",
    "era": "Medieval",
    "summary": "旁遮普爱情史诗，河与墓园。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "Pakistan·因陀罗耆特",
    "en": "Indrajit's Brahmastra (Pakistan)",
    "country": "Pakistan",
    "region": "SouthAsia",
    "lat": 33.37,
    "lng": 72.64,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "罗摩衍那支线在次大陆西北流传。",
    "sourceType": "Epic",
    "confidence": "Medium"
  },
  {
    "cn": "Turkey·德尔格鹅传说",
    "en": "Grey Wolf Ergenekon (Turkey)",
    "country": "Turkey",
    "region": "PersiaArabia",
    "lat": 39.31,
    "lng": 32.04,
    "category": "Moon",
    "era": "Medieval",
    "summary": "突厥系民族出山建国神话。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Turkey·克尔巴特·加尔普",
    "en": "Köroğlu Epic (Turkey)",
    "country": "Turkey",
    "region": "PersiaArabia",
    "lat": 39.62,
    "lng": 32.45,
    "category": "Fire",
    "era": "Folk",
    "summary": "盲父之子反抗权贵，安纳托利亚口传。",
    "sourceType": "Epic",
    "confidence": "Low"
  },
  {
    "cn": "Spain·熙德之歌",
    "en": "Cantar de Mio Cid (Spain)",
    "country": "Spain",
    "region": "Mediterranean",
    "lat": 39.8,
    "lng": -4.52,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "流亡骑士与瓦伦西亚。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "Spain·圣雅各之星路",
    "en": "Camino de Santiago Lore (Spain)",
    "country": "Spain",
    "region": "Mediterranean",
    "lat": 40.11,
    "lng": -4.11,
    "category": "Moon",
    "era": "Medieval",
    "summary": "贝壳路与星象引导。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Poland·克拉克王与龙",
    "en": "Krakus and the Wawel Dragon (Poland)",
    "country": "Poland",
    "region": "SlavicBalkan",
    "lat": 51.61,
    "lng": 20.19,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "克拉科夫伏龙与羊皮桶。",
    "sourceType": "Legend",
    "confidence": "High"
  },
  {
    "cn": "Poland·华沙美人鱼",
    "en": "Warsaw Mermaid (Poland)",
    "country": "Poland",
    "region": "SlavicBalkan",
    "lat": 51.92,
    "lng": 20.6,
    "category": "Love",
    "era": "Folk",
    "summary": "盾与剑的城市象征叙事。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Ukraine·库帕拉仲夏",
    "en": "Kupala Night (Ukraine)",
    "country": "Ukraine",
    "region": "SlavicBalkan",
    "lat": 49.83,
    "lng": 29.7,
    "category": "Fire",
    "era": "Folk",
    "summary": "寻蕨花与渡河，斯拉夫节令。",
    "sourceType": "Folk Tale",
    "confidence": "Medium"
  },
  {
    "cn": "Ukraine·哥萨克马迈",
    "en": "Cossack Mamay (Ukraine)",
    "country": "Ukraine",
    "region": "SlavicBalkan",
    "lat": 50.14,
    "lng": 30.11,
    "category": "Sun",
    "era": "Folk",
    "summary": "游侠与班杜拉琴，草原意象。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Brazil·伊拉帕朗格阿纳",
    "en": "Iara River Spirit (Brazil)",
    "country": "Brazil",
    "region": "Americas",
    "lat": -16.4,
    "lng": -48.75,
    "category": "Moon",
    "era": "Folk",
    "summary": "亚马逊河女妖与溺水。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Brazil·博伊塔塔火蛇",
    "en": "Boitatá Fire Serpent (Brazil)",
    "country": "Brazil",
    "region": "Americas",
    "lat": -16.09,
    "lng": -48.34,
    "category": "Dragon",
    "era": "Folk",
    "summary": "湿地磷火与护林精怪。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Canada·温尼佩格湖怪",
    "en": "Manipogo Lore (Canada)",
    "country": "Canada",
    "region": "Americas",
    "lat": 44.8,
    "lng": -76.52,
    "category": "Dragon",
    "era": "Folk",
    "summary": "草原省湖怪口述。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Canada·因纽特月父",
    "en": "Inuit Moon Father (Canada)",
    "country": "Canada",
    "region": "Americas",
    "lat": 45.11,
    "lng": -76.11,
    "category": "Moon",
    "era": "Folk",
    "summary": "极地月相与家庭伦理。",
    "sourceType": "Myth",
    "confidence": "Low"
  },
  {
    "cn": "Indonesia·加鲁达救母",
    "en": "Garuda Frees His Mother (Indonesia)",
    "country": "Indonesia",
    "region": "Oceania",
    "lat": -6.82,
    "lng": 106.03,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "神鸟与蛇族誓约，爪哇宫廷叙事。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Indonesia·伦卡邦女王",
    "en": "Queen of Southern Seas (Indonesia)",
    "country": "Indonesia",
    "region": "Oceania",
    "lat": -6.51,
    "lng": 106.44,
    "category": "Love",
    "era": "Folk",
    "summary": "南海女王与苏丹婚誓，争议性民间信仰。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Philippines·马拉卡南宫精怪",
    "en": "Malakas at Maganda (Philippines)",
    "country": "Philippines",
    "region": "Oceania",
    "lat": 13.98,
    "lng": 120.16,
    "category": "Love",
    "era": "Ancient",
    "summary": "竹中生第一对男女，他加禄创世。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Philippines·马林杜克猴月",
    "en": "Monkey and the Turtle (Philippines)",
    "country": "Philippines",
    "region": "Oceania",
    "lat": 14.29,
    "lng": 120.57,
    "category": "Moon",
    "era": "Folk",
    "summary": "龟猴斗智，广泛东南亚同源。",
    "sourceType": "Folk Tale",
    "confidence": "High"
  },
  {
    "cn": "Thailand·拉玛坚猴军",
    "en": "Ramakien Monkey Army (Thailand)",
    "country": "Thailand",
    "region": "Oceania",
    "lat": 13.14,
    "lng": 99.68,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "泰国版罗摩史诗与哈奴曼。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "Thailand·娜迦与湄公河",
    "en": "Naga of the Mekong (Thailand)",
    "country": "Thailand",
    "region": "Oceania",
    "lat": 13.45,
    "lng": 100.09,
    "category": "Flood",
    "era": "Folk",
    "summary": "火球节与河龙信仰。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Malaysia·汉都亚与海盗",
    "en": "Hang Tuah Legends (Malaysia)",
    "country": "Malaysia",
    "region": "Oceania",
    "lat": 2.52,
    "lng": 100.87,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "马来勇士与忠诚考验。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Malaysia·庞南岸海祭",
    "en": "Bunga Emas Sea Rite (Malaysia)",
    "country": "Malaysia",
    "region": "Oceania",
    "lat": 2.83,
    "lng": 101.28,
    "category": "Moon",
    "era": "Folk",
    "summary": "王室与暹罗交往的仪式叙事。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Bangladesh·格西拉贾尔",
    "en": "Gazi Pir River Lore (Bangladesh)",
    "country": "Bangladesh",
    "region": "SouthAsia",
    "lat": 23.19,
    "lng": 89.59,
    "category": "Flood",
    "era": "Folk",
    "summary": "穆斯林圣徒与鳄鱼驯服。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Bangladesh·迈门辛虎女",
    "en": "Behula and Lakhindar (Bangladesh)",
    "country": "Bangladesh",
    "region": "SouthAsia",
    "lat": 23.5,
    "lng": 90,
    "category": "Love",
    "era": "Folk",
    "summary": "蛇咬与冥府寻夫，东孟加拉史诗。",
    "sourceType": "Epic",
    "confidence": "Medium"
  },
  {
    "cn": "Nepal·库玛丽活女神",
    "en": "Kumari Living Goddess (Nepal)",
    "country": "Nepal",
    "region": "SouthAsia",
    "lat": 27.1,
    "lng": 84.5,
    "category": "Princess",
    "era": "Folk",
    "summary": "女童化身杜尔迦，王室与宗教。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Nepal·雪人夜话",
    "en": "Yeti Oral Lore (Nepal)",
    "country": "Nepal",
    "region": "SouthAsia",
    "lat": 27.41,
    "lng": 84.91,
    "category": "Dragon",
    "era": "Folk",
    "summary": "喜马拉雅雪人与商队。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Sri Lanka·维阇耶王子登陆",
    "en": "Prince Vijaya Landing (Sri Lanka)",
    "country": "Sri Lanka",
    "region": "SouthAsia",
    "lat": 6.31,
    "lng": 79.04,
    "category": "Sun",
    "era": "Ancient",
    "summary": "狮子血统与僧伽罗王统起点。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Sri Lanka·佛牙节巡游",
    "en": "Esala Perahera Lore (Sri Lanka)",
    "country": "Sri Lanka",
    "region": "SouthAsia",
    "lat": 6.62,
    "lng": 79.45,
    "category": "Moon",
    "era": "Medieval",
    "summary": "圣象驮佛牙，康提传统。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Jordan·佩特拉藏宝",
    "en": "Petra Treasury Lore (Jordan)",
    "country": "Jordan",
    "region": "PersiaArabia",
    "lat": 31.33,
    "lng": 35.09,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "玫瑰城与纳巴泰宝藏传说。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Jordan·摩西泉",
    "en": "Moses' Spring at Petra (Jordan)",
    "country": "Jordan",
    "region": "PersiaArabia",
    "lat": 31.64,
    "lng": 35.5,
    "category": "Flood",
    "era": "Ancient",
    "summary": "击石出水叙事的地方层叠。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Israel·所罗门判婴",
    "en": "Solomon's Judgment (Israel)",
    "country": "Israel",
    "region": "PersiaArabia",
    "lat": 31.15,
    "lng": 34.39,
    "category": "Princess",
    "era": "Ancient",
    "summary": "智慧王与真假母亲。",
    "sourceType": "Legend",
    "confidence": "High"
  },
  {
    "cn": "Israel·莉莉丝与红海",
    "en": "Lilith in Late Lore (Israel)",
    "country": "Israel",
    "region": "PersiaArabia",
    "lat": 31.46,
    "lng": 34.8,
    "category": "Moon",
    "era": "Medieval",
    "summary": "夜妖文本争议，民间与卡巴拉叠合。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Georgia·阿米拉尼锁链",
    "en": "Amirani Chained Hero (Georgia)",
    "country": "Georgia",
    "region": "PersiaArabia",
    "lat": 41.1,
    "lng": 43.97,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "高加索普罗米修斯式英雄。",
    "sourceType": "Epic",
    "confidence": "Medium"
  },
  {
    "cn": "Georgia·金羊毛科尔喀斯",
    "en": "Colchis Golden Fleece (Georgia)",
    "country": "Georgia",
    "region": "PersiaArabia",
    "lat": 41.41,
    "lng": 44.38,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "希腊史诗中的格鲁吉亚海岸。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Romania·斯特里戈伊吸血鬼",
    "en": "Strigoi Lore (Romania)",
    "country": "Romania",
    "region": "SlavicBalkan",
    "lat": 43.81,
    "lng": 25.28,
    "category": "Moon",
    "era": "Folk",
    "summary": "不死者与大蒜十字架，前现代民俗。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Romania·马鲁列什蒂口传",
    "en": "Mărțișor Spring Thread (Romania)",
    "country": "Romania",
    "region": "SlavicBalkan",
    "lat": 44.12,
    "lng": 25.69,
    "category": "Love",
    "era": "Folk",
    "summary": "红白绳与春天精灵。",
    "sourceType": "Folk Tale",
    "confidence": "Low"
  },
  {
    "cn": "Morocco·丹吉尔海格力斯柱",
    "en": "Pillars of Hercules Tangier (Morocco)",
    "country": "Morocco",
    "region": "Africa",
    "lat": 33.35,
    "lng": -7.67,
    "category": "Sun",
    "era": "Ancient",
    "summary": "古典地理想象与海峡。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Morocco·贾努比亚精灵",
    "en": "Jinniya Desert Lore (Morocco)",
    "country": "Morocco",
    "region": "Africa",
    "lat": 33.66,
    "lng": -7.26,
    "category": "Fire",
    "era": "Folk",
    "summary": "撒哈拉绿洲与精怪。",
    "sourceType": "Folk Tale",
    "confidence": "Low"
  },
  {
    "cn": "Tanzania·乞力马扎罗雪灵",
    "en": "Kilimanjaro Snow Spirit (Tanzania)",
    "country": "Tanzania",
    "region": "Africa",
    "lat": -7.41,
    "lng": 38.39,
    "category": "Moon",
    "era": "Folk",
    "summary": "赤道雪峰的口述解释。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Tanzania·辛巴威式石城记忆",
    "en": "Swahili Coast Lore (Tanzania)",
    "country": "Tanzania",
    "region": "Africa",
    "lat": -7.1,
    "lng": 38.8,
    "category": "Sun",
    "era": "Medieval",
    "summary": "东非海岸贸易城邦传说。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Argentina·高乔马丁·菲耶罗",
    "en": "Martín Fierro (Argentina)",
    "country": "Argentina",
    "region": "Americas",
    "lat": -35.22,
    "lng": -59.2,
    "category": "Love",
    "era": "Folk",
    "summary": "草原 gaucho 史诗与身份。",
    "sourceType": "Epic",
    "confidence": "Medium"
  },
  {
    "cn": "Argentina·巴塔哥尼亚巨人",
    "en": "Patagonian Giant Lore (Argentina)",
    "country": "Argentina",
    "region": "Americas",
    "lat": -34.91,
    "lng": -58.79,
    "category": "Dragon",
    "era": "Folk",
    "summary": "殖民探险与土著污名化叙事，存争议。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Chile·阿里卡矿灵",
    "en": "Atacama Mine Spirits (Chile)",
    "country": "Chile",
    "region": "Americas",
    "lat": -34.07,
    "lng": -71.49,
    "category": "Moon",
    "era": "Folk",
    "summary": "硝石沙漠与矿工口述。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Colombia·黄金国",
    "en": "El Dorado Lake Rite (Colombia)",
    "country": "Colombia",
    "region": "Americas",
    "lat": 4.09,
    "lng": -74.89,
    "category": "Sun",
    "era": "Ancient",
    "summary": "镀金王与湖中献金仪式。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Mongolia·长生天苍狼白鹿",
    "en": "Eternal Blue Sky Wolf (Mongolia)",
    "country": "Mongolia",
    "region": "EastAsia",
    "lat": 47.3,
    "lng": 106.1,
    "category": "Love",
    "era": "Ancient",
    "summary": "苍狼白鹿配偶，游牧起源神话。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Saudi Arabia·沙漠精灵与旅人",
    "en": "Jinn of the Empty Quarter (Saudi Arabia)",
    "country": "Saudi Arabia",
    "region": "PersiaArabia",
    "lat": 24.09,
    "lng": 45.86,
    "category": "Fire",
    "era": "Folk",
    "summary": "沙漠精怪与旅人。",
    "sourceType": "Folk Tale",
    "confidence": "Low"
  },
  {
    "cn": "Syria·巴尔米拉女王",
    "en": "Zenobia of Palmyra (Syria)",
    "country": "Syria",
    "region": "PersiaArabia",
    "lat": 32.89,
    "lng": 35.47,
    "category": "Princess",
    "era": "Ancient",
    "summary": "沙漠女王抗罗马。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Lebanon·欧罗巴与黎巴嫩雪松",
    "en": "Cedars of Lebanon Lore (Lebanon)",
    "country": "Lebanon",
    "region": "PersiaArabia",
    "lat": 33.27,
    "lng": 34.68,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "腓尼基与神木贸易神话层叠。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Armenia·诺亚方舟停亚拉腊",
    "en": "Ararat Landing Lore (Armenia)",
    "country": "Armenia",
    "region": "PersiaArabia",
    "lat": 39.56,
    "lng": 43.69,
    "category": "Flood",
    "era": "Ancient",
    "summary": "洪水叙事的山岳记忆。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Portugal·法蒂玛牧童异象",
    "en": "Our Lady of Fatima Vision (Portugal)",
    "country": "Portugal",
    "region": "Mediterranean",
    "lat": 38.1,
    "lng": -9.96,
    "category": "Sun",
    "era": "Folk",
    "summary": "20 世纪牧童异象，宗教口述。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Sweden·弗雷与斯基布拉尼尔",
    "en": "Freyr's Ship Skíðblaðnir (Sweden)",
    "country": "Sweden",
    "region": "NordicCeltic",
    "lat": 58.71,
    "lng": 17.25,
    "category": "Love",
    "era": "Ancient",
    "summary": "丰饶神与折叠船。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Denmark·小美人鱼",
    "en": "Little Mermaid Tale (Denmark)",
    "country": "Denmark",
    "region": "NordicCeltic",
    "lat": 55.06,
    "lng": 11.75,
    "category": "Love",
    "era": "Folk",
    "summary": "安徒生海泡沫灵魂。",
    "sourceType": "Fairy Tale",
    "confidence": "High"
  },
  {
    "cn": "Finland·卡勒瓦拉三宝磨",
    "en": "Sampo in Kalevala (Finland)",
    "country": "Finland",
    "region": "NordicCeltic",
    "lat": 59.55,
    "lng": 24.12,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "魔法磨与北地英雄歌。",
    "sourceType": "Epic",
    "confidence": "High"
  },
  {
    "cn": "Iceland·红胡子埃里克萨迦",
    "en": "Erik the Red Saga (Iceland)",
    "country": "Iceland",
    "region": "NordicCeltic",
    "lat": 63.53,
    "lng": -22.76,
    "category": "Fire",
    "era": "Medieval",
    "summary": "维京西航与冰岛萨迦。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Faroe Islands·法罗鸟崖精怪",
    "en": "Cliff Troll Lore (Faroe Islands)",
    "country": "Faroe Islands",
    "region": "NordicCeltic",
    "lat": 61.39,
    "lng": -7.59,
    "category": "Dragon",
    "era": "Folk",
    "summary": "北大西洋岛链口述。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Czech Republic·好兵帅克",
    "en": "Švejk Satire Lore (Czech Republic)",
    "country": "Czech Republic",
    "region": "SlavicBalkan",
    "lat": 49.46,
    "lng": 13.62,
    "category": "Moon",
    "era": "Folk",
    "summary": "民间机智与奥匈军营（文学民俗化）。",
    "sourceType": "Folk Tale",
    "confidence": "Low"
  },
  {
    "cn": "Hungary·图兰神鹰",
    "en": "Turul Bird Lore (Hungary)",
    "country": "Hungary",
    "region": "SlavicBalkan",
    "lat": 46.88,
    "lng": 18.22,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "神鹰与王权。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Serbia·科索沃黑鸟场",
    "en": "Kosovo Field Epic (Serbia)",
    "country": "Serbia",
    "region": "SlavicBalkan",
    "lat": 44.17,
    "lng": 19.63,
    "category": "Fire",
    "era": "Medieval",
    "summary": "战败与圣王记忆。",
    "sourceType": "Epic",
    "confidence": "Medium"
  },
  {
    "cn": "Bulgaria·萨摩迪瓦山灵",
    "en": "Samodiva Mountain (Bulgaria)",
    "country": "Bulgaria",
    "region": "SlavicBalkan",
    "lat": 42.08,
    "lng": 22.5,
    "category": "Moon",
    "era": "Folk",
    "summary": "金发女妖与舞圈。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Croatia·亚得里亚塞壬",
    "en": "Adriatic Siren Lore (Croatia)",
    "country": "Croatia",
    "region": "SlavicBalkan",
    "lat": 45.19,
    "lng": 15.16,
    "category": "Love",
    "era": "Folk",
    "summary": "海岛与歌声危险。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Slovakia·塔特拉山精",
    "en": "Tatra Dwarf Lore (Slovakia)",
    "country": "Slovakia",
    "region": "SlavicBalkan",
    "lat": 47.53,
    "lng": 16.29,
    "category": "Princess",
    "era": "Folk",
    "summary": "矿与守护。",
    "sourceType": "Folk Tale",
    "confidence": "Low"
  },
  {
    "cn": "Algeria·廷吉塔纳遗迹灵",
    "en": "Tipasa Ruins Lore (Algeria)",
    "country": "Algeria",
    "region": "Africa",
    "lat": 36.13,
    "lng": 2.24,
    "category": "Sun",
    "era": "Folk",
    "summary": "海岸古城与幽灵叙事。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Tunisia·迦太基狄多",
    "en": "Dido of Carthage (Tunisia)",
    "country": "Tunisia",
    "region": "Africa",
    "lat": 36.19,
    "lng": 9.36,
    "category": "Love",
    "era": "Ancient",
    "summary": "建城与埃涅阿斯悲剧。",
    "sourceType": "Legend",
    "confidence": "High"
  },
  {
    "cn": "Congo·刚果河妈妈瓦塔",
    "en": "Congo River Mami Wata (Congo)",
    "country": "Congo",
    "region": "Africa",
    "lat": -4.95,
    "lng": 14.49,
    "category": "Flood",
    "era": "Folk",
    "summary": "水母亲形象跨大西洋。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "Guatemala·波波尔乌创世",
    "en": "Popol Vuh Creation (Guatemala)",
    "country": "Guatemala",
    "region": "Americas",
    "lat": 14.01,
    "lng": -91.37,
    "category": "Sun",
    "era": "Ancient",
    "summary": "玉米人神话，基切圣书。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Bolivia·的的喀喀太阳岛",
    "en": "Isla del Sol Lore (Bolivia)",
    "country": "Bolivia",
    "region": "Americas",
    "lat": -17.12,
    "lng": -68.97,
    "category": "Sun",
    "era": "Ancient",
    "summary": "印加起源圣地。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "New Zealand·毛伊钓岛",
    "en": "Māui Fishes the North (New Zealand)",
    "country": "New Zealand",
    "region": "Oceania",
    "lat": -41.91,
    "lng": 173.96,
    "category": "Dragon",
    "era": "Ancient",
    "summary": "半神兄弟与北岛。",
    "sourceType": "Myth",
    "confidence": "High"
  },
  {
    "cn": "Samoa·塔加洛阿创世",
    "en": "Tagaloa Creation (Samoa)",
    "country": "Samoa",
    "region": "Oceania",
    "lat": -14.38,
    "lng": -172.92,
    "category": "Moon",
    "era": "Ancient",
    "summary": "波利尼西亚高位神。",
    "sourceType": "Myth",
    "confidence": "Medium"
  },
  {
    "cn": "Fiji·德杰尼鱼人",
    "en": "Daucina Fish Lore (Fiji)",
    "country": "Fiji",
    "region": "Oceania",
    "lat": -18.74,
    "lng": 177.63,
    "category": "Flood",
    "era": "Folk",
    "summary": "海洋变形者。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Papua New Guinea·哈根山灵",
    "en": "Hagen Spirit Lore (Papua New Guinea)",
    "country": "Papua New Guinea",
    "region": "Oceania",
    "lat": -10.1,
    "lng": 146.36,
    "category": "Fire",
    "era": "Folk",
    "summary": "高地部族与灵界。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Cambodia·吴哥那伽栏杆",
    "en": "Nāga Balustrade Lore (Cambodia)",
    "country": "Cambodia",
    "region": "Oceania",
    "lat": 10.94,
    "lng": 104.11,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "蛇神与王城水道。",
    "sourceType": "Legend",
    "confidence": "Medium"
  },
  {
    "cn": "England·高文绿骑士抄本",
    "en": "Gawain Manuscript Lore (England)",
    "country": "England",
    "region": "NordicCeltic",
    "lat": 50.88,
    "lng": -0.94,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "14 世纪头韵诗与威尔士边界。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Scotland·尼斯湖水怪",
    "en": "Loch Ness Lore (Scotland)",
    "country": "Scotland",
    "region": "NordicCeltic",
    "lat": 55.33,
    "lng": -4.01,
    "category": "Dragon",
    "era": "Folk",
    "summary": "现代民俗与旅游叙事。",
    "sourceType": "Legend",
    "confidence": "Low"
  },
  {
    "cn": "Wales·红龙与白龙",
    "en": "Red White Dragon Dream (Wales)",
    "country": "Wales",
    "region": "NordicCeltic",
    "lat": 50.86,
    "lng": -4,
    "category": "Dragon",
    "era": "Medieval",
    "summary": "梅林预言与威尔士象征。",
    "sourceType": "Legend",
    "confidence": "Medium"
  }
];
